version: '3.9'

services:
  devcontainer:
    profiles: ['dev']
    user: dev
    working_dir: /home/dev/main
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "echo 'devcontainer is started'; while sleep 1000; do :; done"
    volumes:
      - ./:/home/dev/main:cached
      - node_modules:/home/dev/main/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  node_modules:
