name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [12, 14, 16]

    runs-on: ubuntu-latest

    name: Validate on Node v${{ matrix.node }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
